services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blank_next_app:v1.2
    container_name: blank_next_app
    
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
